[default]
EXTENSIONS= [
	"inventory_control.ext.authentication:init_app",
	"inventory_control.ext.db:init_app",	
	"inventory_control.ext.migrations:init_app",
	"inventory_control.ext.api:init_app",
	"inventory_control.ext.serialization:init_app"

]
SQLALCHEMY_TRACK_MODIFICATIONS=true
SECRET_KEY="do not read this, its secret"
[development]
SQLALCHEMY_DATABASE_URI = "mysql://inventory_control@localhost/inventory_control"
[testing]
SQLALCHEMY_DATABASE_URI = "mysql://inventory_control@localhost/inventory_control_test"

