[default]
EXTENSIONS= [
	"inventory_control.ext.db:init_app",	
	"inventory_control.ext.migrations:init_app"
	"inventory_control.ext.api:init_app"
]
SQLALCHEMY_TRACK_MODIFICATIONS=true
[development]
SQLALCHEMY_DATABASE_URI = "mysql://inventory_control@localhost/inventory_control"
[testing]
SQLALCHEMY_DATABASE_URI = "mysql://inventory_control@localhost/inventory_control"

